version: "3.3"

services:

  app_server:
    image: saarthak08/fsp-backend
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db  
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure


  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_DATABASE: fsp
      MYSQL_USER: Saarthak
      MYSQL_PASSWORD: testing
      MYSQL_ROOT_PASSWORD: root

    
  
  visualizer:
    image: dockersamples/visualizer
    ports:
      - "3000:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  backend:

volumes:
  db-data:
